# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - bash: mkdir -p julia; curl -s https://julialang-s3.julialang.org/bin/linux/x64/1.1/julia-1.1.0-linux-x86_64.tar.gz | tar xzvf - -C julia/
    displayName: 'Download JuliaLang'
  - bash: sudo ln -s "$(pwd)"/julia/julia-1.1.0/bin/julia /usr/local/bin/julia
    displayName: 'Symbolic link julia into /usr/local/bin/julia'
  - bash: julia scripts/install_packages.jl
    displayName: 'Install dependencies'
  - bash: julia src/jmo.jl -h Binaries/ObjcThin
    displayName: 'Show header of ObjcThin binary'
